In [1]:
import numpy as np
import pandas as pd

In [2]:
# 每行是用户的评价，每列是用户对某本书的评价
rating_matrix = np.array(
    [[4,3,0,0,5,0],
     [5,0,4,0,4,0],
     [4,0,5,3,4,0],
     [0,3,0,0,0,5],
     [0,4,0,0,0,4],
     [0,0,2,4,0,5]
    ]
)

In [3]:
from sklearn.metrics.pairwise import cosine_similarity
user_sim = cosine_similarity(rating_matrix)
user_sim

array([[1.        , 0.74926865, 0.62667956, 0.21828206, 0.3       ,
        0.        ],
       [0.74926865, 1.        , 0.91301651, 0.        , 0.        ,
        0.1579597 ],
       [0.62667956, 0.91301651, 1.        , 0.        , 0.        ,
        0.40368671],
       [0.21828206, 0.        , 0.        , 1.        , 0.9701425 ,
        0.63913749],
       [0.3       , 0.        , 0.        , 0.9701425 , 1.        ,
        0.52704628],
       [0.        , 0.1579597 , 0.40368671, 0.63913749, 0.52704628,
        1.        ]])

In [4]:
book_sim = cosine_similarity(rating_matrix.T)
book_sim

array([[1.        , 0.27258651, 0.7897985 , 0.31788777, 0.98245614,
        0.        ],
       [0.27258651, 1.        , 0.        , 0.        , 0.34073314,
        0.65441051],
       [0.7897985 , 0.        , 1.        , 0.68572751, 0.71081865,
        0.18349396],
       [0.31788777, 0.        , 0.68572751, 1.        , 0.31788777,
        0.49236596],
       [0.98245614, 0.34073314, 0.71081865, 0.31788777, 1.        ,
        0.        ],
       [0.        , 0.65441051, 0.18349396, 0.49236596, 0.        ,
        1.        ]])

In [5]:
# 用户1对所有6本书的评分
print(rating_matrix[0])

# 用户对第3本书和其它6本书的相似度, 可以看到它和第2本书毫无相似之处，而和第1本书相似度最高。
print(book_sim[2])


[4 3 0 0 5 0]
[0.7897985  0.         1.         0.68572751 0.71081865 0.18349396]


In [6]:
#用户1，对第3本书的评分
s_3 = np.dot(rating_matrix[0] ,book_sim[2]) /(book_sim[2][0]+book_sim[2][4])
s_3

4.473684210526316

In [7]:
#用户1，对第4本书的评分

print(book_sim[3])
s_4 = np.dot(rating_matrix[0] ,book_sim[3]) /(book_sim[3][0]+book_sim[3][4])
s_4

[0.31788777 0.         0.68572751 1.         0.31788777 0.49236596]


4.5

In [8]:
#用户1，对第6本书的评分

print(book_sim[5])
s_4 = np.dot(rating_matrix[0] ,book_sim[5]) /(book_sim[5][1])
s_4

[0.         0.65441051 0.18349396 0.49236596 0.         1.        ]


3.0

In [9]:
# 总结： sklearn.metrics.pairwise.cosine_similarity 其实是计算一个矩阵内的列向量之间的点积，从几何角度看，就是计算两个向量的点积。
