In [1]:
import numpy as np
import pandas as pd

In [2]:
users = ['u1','u2','u3','u4','u5','u6']
print(users)

['u1', 'u2', 'u3', 'u4', 'u5', 'u6']


In [3]:
rating_matrix = np.array(
    [[4,3,0,0,5,0],
     [5,0,4,0,4,0],
     [4,0,5,3,4,0],
     [0,3,0,0,0,5],
     [0,4,0,0,0,4],
     [0,0,2,4,0,5]
    ]
)

In [4]:
rating_matrix.shape

(6, 6)

In [5]:
rating_matrix.dtype

dtype('int64')

In [6]:
# [0, :]: 在这个上下文中，0是表示行索引，:表示选择该行的所有列。因此，rating_matrix[0, :]选择了矩阵的第一行的所有元素。
rating_matrix[0,:]

array([4, 3, 0, 0, 5, 0])

In [7]:
# rating_matrix[:，0]选择了矩阵的第一列的所有元素。
rating_matrix[:,0]

array([4, 5, 4, 0, 0, 0])

In [8]:
# [:, 0:2]: 在这个上下文中，:表示选择所有行，而0:2表示选择列索引为0到1（不包括2）的所有列。因此，rating_matrix[:, 0:2]选择了矩阵的所有行和第一列到第二列的所有元素。
rating_matrix[:,0:2]

array([[4, 3],
       [5, 0],
       [4, 0],
       [0, 3],
       [0, 4],
       [0, 0]])

In [9]:
rating_matrix[2,2]

5

# 基于欧氏距离计算两个向量之间的距离

In [10]:
# rating_matrix[0, :]: 这是矩阵的第一行。
# rating_matrix[1, :]: 这是矩阵的第二行。
# rating_matrix[0, :] - rating_matrix[1, :]: 这是两行元素对应相减，得到一个新的行向量。
# np.square(...): 这是对新行向量中的每个元素进行平方操作。
# np.sum(...): 这是对平方后的元素进行求和操作。
# np.sqrt(...): 最后，对求和后的结果取平方根，得到欧氏距离。
# 简而言之，这行代码计算了矩阵的第一行与第二行之间的欧氏距离，并将结果存储在变量dist中。

dist = np.sqrt(np.sum(np.square(rating_matrix[0,:]-rating_matrix[1,:])))

In [11]:
dist

5.196152422706632

In [12]:
rating_matrix[0,:]- rating_matrix[1,:]

array([-1,  3, -4,  0,  1,  0])

In [13]:
np.square(rating_matrix[0,:]-rating_matrix[1,:])

array([ 1,  9, 16,  0,  1,  0])

In [14]:
np.sum(np.square(rating_matrix[0,:]-rating_matrix[1,:]))

27

In [15]:
np.sqrt(np.sum(np.square(rating_matrix[0,:]-rating_matrix[1,:])))

5.196152422706632

In [16]:
dist = np.zeros_like(rating_matrix)

for i in range(rating_matrix.shape[0]):
    for j in range(rating_matrix.shape[0]):
        dist[i,j] = np.sqrt(np.sum(np.square(rating_matrix[i,:]-rating_matrix[j,:])))

In [17]:
dist

array([[ 0,  5,  6,  8,  7,  9],
       [ 5,  0,  3,  9,  9,  9],
       [ 6,  3,  0, 10,  9,  8],
       [ 8,  9, 10,  0,  1,  5],
       [ 7,  9,  9,  1,  0,  6],
       [ 9,  9,  8,  5,  6,  0]])

In [18]:
from sklearn.metrics.pairwise import euclidean_distances

In [19]:
dist = euclidean_distances(rating_matrix)

In [20]:
dist

array([[ 0.        ,  5.19615242,  6.63324958,  8.1240384 ,  7.61577311,
         9.74679434],
       [ 5.19615242,  0.        ,  3.31662479,  9.53939201,  9.43398113,
         9.2736185 ],
       [ 6.63324958,  3.31662479,  0.        , 10.        ,  9.89949494,
         8.18535277],
       [ 8.1240384 ,  9.53939201, 10.        ,  0.        ,  1.41421356,
         5.38516481],
       [ 7.61577311,  9.43398113,  9.89949494,  1.41421356,  0.        ,
         6.08276253],
       [ 9.74679434,  9.2736185 ,  8.18535277,  5.38516481,  6.08276253,
         0.        ]])

# 使用点积（余弦相似度）计算向量之间的相似度

In [21]:
def mod(vec):
    return np.sum(vec ** 2) ** 0.5

In [22]:
rating_matrix[0]

array([4, 3, 0, 0, 5, 0])

In [23]:
rating_matrix[0] ** 3

array([ 64,  27,   0,   0, 125,   0])

In [24]:
def sim(vec1,vec2):
    return np.dot(vec1,vec2) / mod(vec1) / mod(vec2)

In [25]:
sim(rating_matrix[0],rating_matrix[1])

0.7492686492653551

In [26]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(rating_matrix)
sim

array([[1.        , 0.74926865, 0.62667956, 0.21828206, 0.3       ,
        0.        ],
       [0.74926865, 1.        , 0.91301651, 0.        , 0.        ,
        0.1579597 ],
       [0.62667956, 0.91301651, 1.        , 0.        , 0.        ,
        0.40368671],
       [0.21828206, 0.        , 0.        , 1.        , 0.9701425 ,
        0.63913749],
       [0.3       , 0.        , 0.        , 0.9701425 , 1.        ,
        0.52704628],
       [0.        , 0.1579597 , 0.40368671, 0.63913749, 0.52704628,
        1.        ]])

In [27]:
rating_matrix

array([[4, 3, 0, 0, 5, 0],
       [5, 0, 4, 0, 4, 0],
       [4, 0, 5, 3, 4, 0],
       [0, 3, 0, 0, 0, 5],
       [0, 4, 0, 0, 0, 4],
       [0, 0, 2, 4, 0, 5]])

# 讨论
数据科学领域有一个很基础、很重要的模型﹣﹣向量空间模型（ Vector Space Model , VSM )。该模型把要研究的对象想象成空间中的一个向量或者一个点，然后通过分析点和点之间的距离或相似性来挖掘出数据内隐藏的信息。

以图2-4所示的用户行为评分矩阵为例，它其实是个二维表格（矩阵从形态上看就是二维表格，相当于数据库中的一张表）。其中的每一行叫作一个样本，每一列叫作样本的一个特征，所以在这份数据集中每个人就是一个样本，每个人有6个特征，特征可以理解为：某个人对于某个物品的喜好度。
array([[4, 3, 0, 0, 5, 0],
       [5, 0, 4, 0, 4, 0],
       [4, 0, 5, 3, 4, 0],
       [0, 3, 0, 0, 0, 5],
       [0, 4, 0, 0, 0, 4],
       [0, 0, 2, 4, 0, 5]])
于是，我们可以想象有一个六维的空间，每个特征（每本书）就是空间的一个维度，然后每个人就是这个六维空间中的一个点，每个点有6个维度（6个特征）。点和点之间的距离是它们”相似度“的一种表现。距离为0就是100%相同（即自身的复制）。

数据科学中的几大类问题都可以用向量空间模型解释。

- 所谓二分类问题就是在空间中找到一个”超平面“把两类数据点完美分开，一旦找到这样的超平面，就可以用进行预测﹣﹣看数据点落在平面的哪一侧来判断它属于哪一个类别。
- 而回归问题则是在空间中找到一个”超平面“，使其”尽可能“地穿过所有的点。这个平面既可以用一个方程表达，也可以用于未来的预测。
- 聚类问题是根据样本之间的相似程度，把样本分成几组，让每组内部的样本尽可能相似，而组和组之间的样本则尽可能不相似。一旦完成这样的分组，就可以进行分析，找出组和组之间的区别以指导企业运营。
聚类典型的应用场景有用户价值分析和精细化运营。比如，早期的中国移动的电话卡分成神州行、动感地带、全球通3个品牌。这3个品牌针对不同的用户群体，提供不同的增值服务。这种用户群体的区分，通常就是用聚类完成的。