In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,3,1,2])

In [3]:
# 向量的二范数
np.linalg.norm(a)

7.416198487095663

In [4]:
np.linalg.norm(b)

5.196152422706632

In [4]:
# 比较两个相量是否相同
a == b

array([False, False,  True, False, False])

In [9]:
if np.all(a == b):
    print("两个向量相同")
else :
    print("不同")

不同


In [7]:
np.any(a==b)

True

In [8]:
np.all(a==b)

False

In [5]:
# 向量加减法
a + b

array([3, 5, 6, 5, 7])

In [13]:
a - b

array([-1, -1,  0,  3,  3])

In [14]:
a + 2

array([3, 4, 5, 6, 7])

In [17]:
# 向量数乘
a * 2

array([ 2,  4,  6,  8, 10])

In [16]:
a + b

array([3, 5, 6, 5, 7])

In [6]:
# 向量线性组合
a * 2 + b * 4

array([10, 16, 18, 12, 18])

In [20]:
# 向量元素相乘
a * b  #element-wise compute

array([ 2,  6,  9,  4, 10])

In [21]:
# 向量点积 （内积）
np.dot(a,b)

31