array 是Python标准库中的一部分，属于 array 模块。
array 提供了一维数组的支持，但不支持多维数组。
它提供了基本的数组操作，但功能相对有限。

In [1]:
from array import array
# 'i' 表示整数类型。可以省略--系统自行推断，可能导致不确定因素
arr = array('i', [1, 2, 3, 4, 5])
arr

array('i', [1, 2, 3, 4, 5])

In [2]:
arr[0]

1

NumPy 中有两种数据结构都可以用于矩阵： ndarray 和 matrix 。 
ndarray (N dimension array) 是个广义的数组，既可以表示向量，也可以表示矩阵，甚至可以表示更高维度的张量。

不同于 array 模块，NumPy的 ndarray 允许混合存储不同数据类型的元素。NumPy 的 ndarray 具有更灵活的数据类型支持，这使得它适用于处理多种数据类型的数组。

In [3]:
import numpy as np
A=np.random.rand(4,4)
A

array([[0.71896944, 0.23824813, 0.56550448, 0.09349141],
       [0.87109237, 0.49673846, 0.78732409, 0.4365423 ],
       [0.85492838, 0.22747272, 0.11887675, 0.14414124],
       [0.63502209, 0.72784778, 0.59847569, 0.72977424]])

matrix是专门针对矩阵的数据结构，是个二维数组。虽然ndarray/matrix两种数据结构都能支持矩阵运算，不过在细节上会有些差异。

In [4]:
# 从ndarray构建matrix
B = np.mat(A)

In [5]:
B

matrix([[0.71896944, 0.23824813, 0.56550448, 0.09349141],
        [0.87109237, 0.49673846, 0.78732409, 0.4365423 ],
        [0.85492838, 0.22747272, 0.11887675, 0.14414124],
        [0.63502209, 0.72784778, 0.59847569, 0.72977424]])

In [6]:
B = np.mat(np.random.rand(4,4))
B

matrix([[0.90109116, 0.7996038 , 0.84580933, 0.30618248],
        [0.4578155 , 0.38159568, 0.14460544, 0.90785895],
        [0.16418719, 0.39579152, 0.5936203 , 0.58816644],
        [0.00102427, 0.38380115, 0.60439107, 0.5316763 ]])

In [7]:
B=np.mat('1 2 3; 4 5 6; 7 8 9')

In [8]:
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

建一个大小为 5x5 的单位矩阵

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.diag([1,2,3,0,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5]])

### 用AA^T创建对称阵

In [11]:
A = np.mat('1 2 3; 4 5 6; 7 8 9')
A * A.T

matrix([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]])

### 矩阵基本运算

In [12]:
A = np.mat('1 2 3; 4 5 6; 7 8 9')
B = np.mat(' 4 5 6; 7 8 9; 10 11 12')

In [13]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
A+B

matrix([[ 5,  7,  9],
        [11, 13, 15],
        [17, 19, 21]])

In [15]:
B = np.mat('4 4 5 6;4 7 8 9;4 10 11 12')
B

matrix([[ 4,  4,  5,  6],
        [ 4,  7,  8,  9],
        [ 4, 10, 11, 12]])

In [16]:
# 维度不同的矩阵相加会出错
A+B

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [ ]:
A * B

In [ ]:
B * A

In [ ]:
A * 10

矩阵求逆

In [ ]:
c = np.mat(np.random.rand(4,4))

In [ ]:
d = c.I

In [ ]:
c*d

In [ ]:
d * c

In [ ]:
c*d == d*c

In [ ]:
A

In [ ]:
# np.linalg: 这是 NumPy 中专门用于线性代数操作的子模块。
# matrix_rank(): 这是 np.linalg 模块中的函数，用于计算矩阵的秩。
np.linalg.matrix_rank(A)

In [ ]:
# det(): 这是 np.linalg 模块中的函数，用于计算矩阵的行列式。
np.linalg.det(A)

In [ ]:
# matrix_rank(): 这是 np.linalg 模块中的函数，用于计算矩阵的秩。
# 对于一个矩阵而言，如果它不是满秩的（秩不等于矩阵的行数或列数），那么它是奇异的，且没有逆矩阵。
# 数学上，一个矩阵是满秩的，当且仅当它的行秩和列秩等于其阶（行数和列数的最小值）。如果一个矩阵不是满秩的，它就是奇异的。奇异矩阵的行列式为零，因为行列式的值表示的是矩阵的缩放因子，而奇异矩阵的缩放因子为零。
# A.I 得到 0 矩阵
A.I

In [ ]:
d = A.I

In [ ]:
A*d

In [ ]:
d * A